# Generated by Django 4.1.7 on 2023-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=200)),
                ('details', models.CharField(default='SOME STRING', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=200)),
                ('position', models.CharField(default='SOME STRING', max_length=200)),
                ('details', models.CharField(default='SOME STRING', max_length=500)),
                ('image', models.CharField(default='SOME STRING', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
